### ISSUE TITLE
Inquiry about some errors in measr package 

### ISSUE THREAD

**Issue by jrachaelahn** [wjakethompson/measr#37]
Hello, 

When running the example code from the measr package, the error in 'dplyr :: select()' persists (File attached).
Would you mind please helping me out with this error?

Thank you
 
 
[Error from measr package.docx](https://github.com/wjakethompson/measr/files/12589529/Error.from.measr.package.docx)

**Comment by wjakethompson** [comment]
Hi @jrachaelahn. I'm unable to reproduce this error locally. From the error message, it appears that something in dplyr is breaking. I would recommend updating the dplyr package. In the session info, it looks like you are using 1.0.10. The current version on CRAN is 1.1.3.
